const DB = {
    empresas:        [],
    colaboradores:   [],
    particulares:    [],
    dados_pedido:    [],
    pedidos:         [],
    ordens:          [],
    orcamentos:      [],
    pecas:           [],
    pecas_pedidos:   [],
    orcamento_itens: [],
    notas_pedido:    [],
    colaboradores_dm:[],
    materia_prima:   [],
    fornecedores:    [],
    historico_precos:[],
    servicos:        [],
    servicos_pedidos:[],
    processos:           [],
    pecas_processos:     [],
    historico_precos_mp:        [],
    historico_precos_processos: [],

    /** UI state */
    expanded:      {},
    clienteFilter: 'todos',
};
